name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get install libboost-dev
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
        env:
          CI: true
         
      - name: Upload artifacts
        uses: actions/checkout@v3
        with:
          name: my-build-artifacts 
          path: test_projects/project1_Simple
          
        
      - name: Test1
        run: |
          ls 
          echo cd test_projects/project1_Simple
          ls 
          echo make test_projects/project1_Simple
          ./analysis
        env:
          CI: true
