name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get install libboost-dev
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
        env:
          CI: true
          
      - name: Test1
        run: |
          echo cd test_projects/project1_Simple
          echo make
          echo ../test_projects/project1_Simple/analysis.exe
          ../test_projects/project1_Simple/analysis.exe 
          mkdir build
          mkdir build/Debug
          cd build
          cmake ..
          cmake --build .
          cd ..
          cd build/Debug
          
        env:
          CI: true
