image: gcc

build:
  stage: build

  script:
    - g++ helloworld.cpp -o mybinary
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  script:
    - ./runmytests.sh

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
