name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: microsoft/setup-vcpkg@v1
        with:
          version: '2023.05.29' 
          architecture: 'x64' 

      - name: Install Boost
        run: vcpkg install boost 

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
        env:
          CI: true
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifacts 
          path: test_projects/project1_Simple
      - name: Test1
        run: |
          cd test_projects/project1_Simple
          make .
        env:
          CI: true