name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get install libboost-dev
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
        env:
          CI: true
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifacts 
          path: test_projects/project1_Simple
      - name: Test1
        run: |
          cd test_projects/project1_Simple
          ls
          make 
          ls 
          ./analysis
          
        env:
          CI: true
