name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get install libboost-dev
          mkdir build
          cd build
          cmake ..
          cmake --build .
        env:
          CI: true
          
      - name: Test1
        run: |
          cd test_projects/project2_Variables
          mkdir build
          cd build
          cmake ..
          cmake --build .
          make
        env:
          CI: true
